services:
  - type: web
    name: romantic-hamilton
    runtime: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUBLIC_SITE_URL
        value: https://romantichamilton.store
